### ISSUE TITLE
Methoden und Klassen kommentieren

### ISSUE THREAD

**Issue by VanSchnitzel** [Waffenfliege/Projekt1WI14A#12]
Mathias, Robert, Jonathan: LogicHandler
Jonathan: DataHandler
Lukas, Jan: ViewHandler etc.

**Comment by UltimateCuB3R** [comment]
ViewHandler ist größtenteils kommentiert, 
@VanSchnitzel du solltest bei deinen Methoden nochmal überprüfen, ob die Kommentare überhaupt so stimmen.

**Comment by VanSchnitzel** [comment]
hast du mir ein beispiel für eine methode wo das nicht stimmt?
