### ISSUE TITLE
Korrektes Zurücksetzen aller Werte bei "neue Berechnung"

### ISSUE THREAD

**Issue by VanSchnitzel** [Waffenfliege/Projekt1WI14A#14]

**Comment by UltimateCuB3R** [comment]
Dafür brauche ich noch eine Methode im DataHandler, die die ArrayList richtig resettet.
Bisher kommt noch eine "ArrayIndexOutOfBounds"-Exception, wenn man nach dem resetten neue Werte eingeben will.

**Comment by VanSchnitzel** [comment]
Ist soweit fertig, oder?

**Comment by UltimateCuB3R** [comment]
Nein, das Eingeben von neuen Klassen klappt immer noch nicht.

**Comment by jkwi14** [comment]
Da von ButtonContainer zwei Objekte erstellt werden (input&output), hat "index=0" im output objekt keinen Einfluss auf den index-wert im input objekt. Deshalb wird vom Input objekt der unveränderte Indexwert (z.B. 4) an den DataHandler übergeben.

**Comment by UltimateCuB3R** [comment]
wir können die Buttons fürs InputPanel vom ButtonContainer wieder in das InputPanel zurückschieben, den ButtonContainer als eigene Klasse brauche ich nur wegen den Buttons im OutputPanel.

Soll ich das so machen?

**Comment by VanSchnitzel** [comment]
Ich habe ein "branch" gemacht, in dem ich das mit den buttons
umstrukturiert habe. der inputcontainer hätte seine eigenen buttons und der
outputcontainer seine eigenen. alles als objekte des entsprechenden
containers angelegt. funktioniert alles, auch die schaubilder, nur, dass
man die tabs nochmal neu füllen müsste.

Wir können das so übernehmen oder bei der alten Version bleiben. Aber ich
finde die Idee nicth gut, dass zwei unterschiedliche Objekte vom gleichen
Konstruktor zurückgegeben werden (das boolean-flag output meine ich).
Also entweder würde ich zwei Klassen daraus machen und bei der aktuellen
Architektur bleiben oder wir legen die buttons direkt in einem
containerpanel in dem entsprechenden input- oder outputpanel an. so hab ich
das in meiner "testversion" mal gemacht.

ich koche gerade noch und meine freundin ist am packen, die geht ja morgen
in den urlaub (ich nicht!). Ich würde also gerne hier noch ein bisschen
zeit mit ihr verbringen und mich dann anschließend nochmal hinsetzen und
das mit dir besprechen. bist du heute abend erreichbar?

Am 4. Februar 2017 um 16:58 schrieb UltimateCuB3R <notifications@github.com>
:

**Comment by UltimateCuB3R** [comment]
Ja, ich bin ab jetzt erreichbar und in Skype online.

**Comment by UltimateCuB3R** [comment]
funktioniert jetzt einwandfrei.
