### ISSUE TITLE
Formelzeichen hinzufügen

### ISSUE THREAD

**Issue by jkwi14** [Waffenfliege/Projekt1WI14A#21]
Können Formelzeichen einfach von einem beliebigen Texteditor zu Eclipse kopiert werden?

**Comment by dwaldmannDE** [comment]
http://stackoverflow.com/questions/456002/displaying-fancy-equations-with-java

LaTeX Renderer for Java.

**Comment by UltimateCuB3R** [comment]
Bisher habe ich das ganze ja über Bilder realisiert.
Im Grunde können wir das ja so lassen und das Layout eben dementsprechend gestalten, wenn sonst kein einfacherer Lösungsweg vorhanden ist.

**Comment by VanSchnitzel** [comment]
Wies aussieht müssen wir die Formeln über Bilder realisieren. 
Aber ich würde die Dinger als PNGs einbinden und den Hintergrund entfernen, dann ist die weiße Fläche nicht da.

**Comment by UltimateCuB3R** [comment]
Hintergrund sollte eh weiß sein, daher entfällt das mit dem Hintergrund entfernen.
Muss jetzt nur noch die Ergebnisse entsprechend formatieren.

**Comment by UltimateCuB3R** [comment]
Ergebnisse werden jetzt korrekt formatiert ausgegeben.
