### ISSUE TITLE
fehlerhafte Darstellung von Umlauten

### ISSUE THREAD

**Issue by dwaldmannDE** [Waffenfliege/Projekt1WI14A#22]
<img width="800" alt="ubersicht" src="https://cloud.githubusercontent.com/assets/25527351/22640629/cffe7dcc-ec53-11e6-9a1e-559e9e8ca805.png">

Umlaute werden noch nicht korrekt kodiert und dargestellt.

**Comment by UltimateCuB3R** [comment]
Der Fehler müsste jetzt behoben sein, hab den Umlaut als Unicode eingefügt.
