### ISSUE TITLE
Eingabe von mehr als 20 Klassen abfangen & abhandeln

### ISSUE THREAD

**Issue by UltimateCuB3R** [Waffenfliege/Projekt1WI14A#25]
Bisher kommt bei der Eingabe der 20. Klasse ein Fehler wegen der Selektion der Tabellenreihe und bei der Eingabe einer 21. Klasse eine Exception "Es wurden bereits 20 Klassen eingegeben!"
-> sollte direkt abgefangen & in das classErrorLabel eingebunden werden.

**Comment by VanSchnitzel** [comment]
Du hast das Label oben schon eingebunden, kannst du das nicht bei dem auch machen? Sonst muss ich erst gucken wie du das gemacht hast. Oder fehlt dir da die richtige Exception?

Bei der Tabelle liegt das am Index, der in InputPanel liegt. der darf natürlich nicht über 19 gehen, was er momentan wohl tut. oder der tabellenindex geht über 19, denn ich dachte dass cih den index der aktuell gewählten klasse begrenzt habe.

**Comment by UltimateCuB3R** [comment]
Es ist keine richtige Exception, sonst hätte ich das direkt gemacht.

Ja kann sein, können wir uns ja nachher mal anschauen.

**Comment by UltimateCuB3R** [comment]
Hab es jetzt einfach so gemacht: der Index wird maximal auf 19 erhöht, damit können nie mehr als 20 Klassen eingegeben werden. Wenn die 20. Klasse abgespeichert wird, wird keine potenzielle 21. Klasse angezeigt, sondern die gerade eingegebene 20. Klasse.
