### ISSUE TITLE
Änderungen von bereits existierenden Klassen werden nicht in die Tabelle übertragen

### ISSUE THREAD

**Issue by VanSchnitzel** [Waffenfliege/Projekt1WI14A#26]
1. 2 Klassen anlegen
2. 1. klasse wählen und ändern
3. "nächste klasse" drücken"

-> DIe tabelle wird nicht aktualisiert, aber wenn man vor oder zurück geht steht der richtige wert da.

**Comment by UltimateCuB3R** [comment]
Hab ich [hier](https://github.com/Waffenfliege/Projekt1WI14A/issues/6) schon gemeldet :P
