### ISSUE TITLE
Gini-Koeffizient in DataHandler einfügen

### ISSUE THREAD

**Issue by UltimateCuB3R** [Waffenfliege/Projekt1WI14A#28]
Gini-Koeffizient-Berechnung wurde von Robert eingefügt, bisher wird die Berechnung aber nirgends ausgeführt und auch noch nicht im ResultSet gespeichert.

**Comment by VanSchnitzel** [comment]
Mach ich

**Comment by UltimateCuB3R** [comment]
Funktioniert einwandfrei.
