### ISSUE TITLE
JFreeChart für Diagrammerstellung?

### ISSUE THREAD

**Issue by UltimateCuB3R** [Waffenfliege/Projekt1WI14A#3]
http://www.jfree.org/jfreechart/

da kann man auch ein Histogramm erstellen.
Ist eine Bibliothek die man einfach ins Projekt einfügen muss.
https://www.tutorialspoint.com/jfreechart/jfreechart_installation.htm

**Comment by Waffenfliege** [comment]
Schaut cool aus, je nachdem ob die vorgelagerte Gruppe so eine Anforderung an uns stellt. Also graphische Darstellung der Ergebnisse.
