### ISSUE TITLE
Klammern unabhängig voneinander anpassbar machen

### ISSUE THREAD

**Issue by UltimateCuB3R** [Waffenfliege/Projekt1WI14A#31]
Klammern unabhängig voneinander anpassbar machen

**Comment by UltimateCuB3R** [comment]
Sind unabhängig voneinander anpassbar, aber es gibt noch Probleme mit der Kombination verschiedener Klammern...

**Comment by jkwi14** [comment]
Klammerprobleme sollten gelöst sein. 
Wenn aufeinandertreffende Klassengrenzen identisch sind, sind alle Klammerkombinationen möglich außer zwei mal Inklusiv. 

Lücken sind immernoch möglich. Aber das haben wir ja so entschieden.
