### ISSUE TITLE
Funktionen der Übersichtstabelle

### ISSUE THREAD

**Issue by Riesenstiel** [Waffenfliege/Projekt1WI14A#35]
Klasse bei Doppelklick nicht aufrufbar/ wird nicht im "Eingabemodus" angezeigt.
Nach Löschung von Datensatz ist Klasse in Tabelle immer noch vorhanden.

Vgl. Testkonzeot 10006

**Comment by UltimateCuB3R** [comment]
- Klasse per Doppelklick nun aufrufbar (man muss auf die Klassennummer klicken)
- Löschen eines Datensatzes nicht vorgesehen!
vgl. #40
