### ISSUE TITLE
Fehlende Fehlermeldungen

### ISSUE THREAD

**Issue by Riesenstiel** [Waffenfliege/Projekt1WI14A#36]
Vgl. 10008 Fehlereingabe Buchstaben Untergrenze
Vgl. 10009 Fehlereingabe Buchstaben Obergrenze
Vgl. 10010 Fehlereingabe Sonderzeichen Untergrenze
Vgl. 10011 Fehlereingabe Sonderzeichen Obergrenze
Vgl. 10015 Leerzeichen Intervallobergrenze
Vgl. 10016 Leerzeichen Intervalluntergrenze
Vgl. 10017 Leerzeichen Zahlen
Vgl. 10018 Leere Eingabefelder
Vgl. 10022 Fehleingabe Buchstabe Absolute Häufigkeit h(K)
Vgl. 10023 Fehleingabe Sonderzeichen Absolute Häufigkeit h(K)
Vgl. 10024 Fehleingabe Leerzeichen Absolute Häufigkeit h(K)
Vgl. 10025 Fehleingabe Leerzeichen Variable z

**Comment by UltimateCuB3R** [comment]
siehe #40
