### ISSUE TITLE
Fehlerhafte Ergebnisse bei x0,05; x0,1; x0,9; d; G

### ISSUE THREAD

**Issue by Riesenstiel** [Waffenfliege/Projekt1WI14A#37]
Vgl. 10004

## Eingabewerte:
Klassen: 
K1 = (35,37] 
K2 = (37,40] 
K3 = (40,43] 
K4 = (43,48] 
 Absolute Häufigkeiten: 
h1 = 1 
h2 = 3 
h3 = 2 
h4 = 1 
 Variable Z:  
z = 35
## Erwartetes Ergebnis:
![image](https://cloud.githubusercontent.com/assets/25662044/22802098/c7c30e0c-ef0f-11e6-8bf5-f92c07bee354.png)

## Tatsächliches Ergebnis:
![image](https://cloud.githubusercontent.com/assets/25662044/22802134/f569b0cc-ef0f-11e6-99d2-14682acbd68d.png)

**Comment by VanSchnitzel** [comment]
Ich finde nur einen möglichen Fehler / Offene Frage: Was passiert bei der Berechnung der ersten beiden Quantile mit dem unteren R-Wert? Ist das dann 0.0? So wirds im Moment gehandhabt, und die ersten beiden Quantile, die eben in der ersten Klasse liegen, sind offenbar falsch.

![image](https://cloud.githubusercontent.com/assets/25294872/22874000/dbe8bec0-f1c3-11e6-920f-8a743d9eb4ed.png)
