### ISSUE TITLE
Fehler bei der Klasseneinteilung und den zugehörigen Klammern

### ISSUE THREAD

**Issue by Riesenstiel** [Waffenfliege/Projekt1WI14A#38]
Die Belegung der Klammern ist nicht korrekt. Korrekt ist: ( ) = ausschließlich; [ ] = einschließlich.

Klassen müssen aneinandergrenzen. Daher ist zum einen die Lücke zwischen K1 und K2 nicht möglich, zum anderen aber auch die Lücke zwischen K2 und K3, die durch den Ausschluss des Wertes 12 in beiden Klassen entsteht (Auf dem Screenshot sind die Klammern noch falsch belegt).

![image](https://cloud.githubusercontent.com/assets/25662044/22802387/e8a20294-ef10-11e6-9858-cea735059c5f.png)

**Comment by UltimateCuB3R** [comment]
siehe #31

**Comment by jkwi14** [comment]
Die Klammerzuweisung einschließlich/ausschließlich ist korrigiert. Zwar nicht von mir aber scheint zu funktionieren. Siehe Screenshot mit gleichen Werten.

Wegen den Lücken haben wir uns dazu entschieden, keine Prüfung zu integrieren. 

![image](https://cloud.githubusercontent.com/assets/25294913/22867423/35f7889c-f188-11e6-93d1-c9718147f59c.png)
