### ISSUE TITLE
Methode: getRelativeOccurences

### ISSUE THREAD

**Issue by Waffenfliege** [Waffenfliege/Projekt1WI14A#4]
Mathias, brauchst du da das Argument sampleSize wirklich? Kannst du das nicht aus der ArrayList rausziehen?

**Comment by VanSchnitzel** [comment]
Doch, aber da  musst du dann jedes mal durch jede Klasse in der Liste durchgehen und die absoluten Häufigkeiten addieren. Es macht Sinn das in eine Methode zu packen. Ich habe gesehen dass du mit dem Gini-Koeffizienten angefangen hast. Ich habe es bisher immer so gemacht, dass der Methodenaufruf als Parameter alle benötigten Werte mitgibt (Klassen, Häufigkeiten, Stichprobengröße etc). Du hast es bisher bei dir so gelöst gehabt dass du die Werte neu berechnest. Man kann beides machen, ich hab mir das auch so überlegt. Aber wir sollten es einheitlich machen. Ich dachte mir, dass es keinen Sinn macht, diese Werte bei jedem zu berechnenden Wert neu zu ermitteln. Stattdessen würde ich die gerade berechneten Werte einfach weitergeben.

**Comment by VanSchnitzel** [comment]
Wie siehts aus Robert, kommt beim Gini ein Wert raus?

**Comment by VanSchnitzel** [comment]
Aktuell wird ja nix im ResultOverview angezeigt, aber liegt das vllcht am fehlenden setter?
