### ISSUE TITLE
Fehlende Fehlermeldung bei der Eingabe von Double-Werten in absolute Häufigkeiten

### ISSUE THREAD

**Issue by Riesenstiel** [Waffenfliege/Projekt1WI14A#41]
![image](https://cloud.githubusercontent.com/assets/25662044/22834093/57035b0e-efb4-11e6-9264-b50cfe038e4f.png)

**Comment by UltimateCuB3R** [comment]
Die Prüfung läuft jetzt nur noch auf positive Integer-Werte.
