### ISSUE TITLE
LableUpdate

### ISSUE THREAD

**Issue by LukeWI** [Waffenfliege/Projekt1WI14A#6]
Nächste/Vorherige Klasse sollen Labels updaten

**Comment by VanSchnitzel** [comment]
Passt soweit, bisher wird aber eine Änderung der Klammern nicht übernommen - muss noch nachgetragen werden

**Comment by UltimateCuB3R** [comment]
Tabelle wird auch nicht aktualisiert wenn man eine vorher eingegebene Klasse ändert.

**Comment by VanSchnitzel** [comment]
gefixt
