### ISSUE TITLE
Änderungen am Fachkonzept

### ISSUE THREAD

**Issue by UltimateCuB3R** [Waffenfliege/Projekt1WI14A#8]
## Von mir vorgeschlagene Änderungen an Fachkonzept Teil 2 (2.0)
- Hover-Designvorgaben überall entfernen
- Navigationspfeile anders gestalten (Benutzerfreundlichkeit?)
- Reiter-Designvorgaben entfernen (so nicht umsetzbar, Standard verwenden)
- Diagramm-Designvorgaben noch fraglich, kommt dann auf Diagramm-Implementierung an
- Bezeichnungen der Komponenten ist nicht auf englisch (entspricht nicht unseren Programmierrichtlinien)
- Vorgaben sagen Double, wir verwenden aber nur Float
- Button "Ohne Z fortfahren" bei Dialogfenster "Eingabemaske Variable Z" entfernen, anderen Button entsprechend umbenennen (Eingabe ist Pflicht!)

**Comment by VanSchnitzel** [comment]
Unterstütze ich so.
