### ISSUE TITLE
Anzeige der berechneten Werte im Ergebnisbildschirm

### ISSUE THREAD

**Issue by VanSchnitzel** [Waffenfliege/Projekt1WI14A#9]
Prüfen, ob eventuell "Value" im outputpanel hardgecoded ist. Eigentlich werden die Werte über  Setter übergeben...

**Comment by UltimateCuB3R** [comment]
In welcher Methode/Klasse wird das denn ausgeführt?
Ich hab da keinen Überblick zurzeit.

**Comment by UltimateCuB3R** [comment]
Anzeige der Ergebnisse funktioniert jetzt.
Layout der Ergebnisanzeige ist auch wie gewünscht.
